site_name: Mondo Documentation
docs_dir: docs
site_dir: docs-site
theme:
  name: 'material'
markdown_extensions:
  - toc:
      permalink: True
nav:
  - index.md
  - analysis.md
  - change-log.md
  - 'Developers guide': developer-guide
    - set-up-docker.md
    - release.md
    - repair-obsoleted-classes.md
